os: Visual Studio 2017

# version format
version: 1.1.{build}

cache:
  - src\packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified

build:
  project: PAYNLSDK\PayNLSdk.csproj
  
before_build:
  - nuget restore

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  
-  # configuration for MASTER branch
  branches:
    only:
      - master

  configuration: Release
  
  artifacts:
    - path: '**\RoodFluweel.PAYNLSDK.*.nupkg' # find all NuGet packages recursively
      name: MyApp
  
  deploy:
    provider: NuGet
    api_key:
      secure: pd9kF0t0Bt6BExgB0t6xEQT9pAlFrRhFZDl6LDGTZjtgaI4nd4ilIongUFWZKLOO
    skip_symbols: false
    artifact: MyApp

-  # configuration for other branches
  configuration: Debug