-
  branches:
    only:
      - master
  configuration: AppVeyor
  artifacts:
    - path: '**\RoodFluweel.PAYNLSDK.*.nupkg' # find all NuGet packages recursively
      name: MyApp
    - path: '**\RoodFluweel.PAYNLSDK.*.snupkg' # find all NuGet PDB packages recursively
      name: MyPdb
  deploy:
    - provider: NuGet
      api_key:
        secure: pd9kF0t0Bt6BExgB0t6xEQT9pAlFrRhFZDl6LDGTZjtgaI4nd4ilIongUFWZKLOO
      skip_symbols: false
      artifact: MyApp
    - provider: NuGet
      api_key:
        secure: pd9kF0t0Bt6BExgB0t6xEQT9pAlFrRhFZDl6LDGTZjtgaI4nd4ilIongUFWZKLOO
      skip_symbols: false
      artifact: MyPdb
  os: Visual Studio 2017
  install:
    - choco install gitversion.portable -pre -y
  assembly_info:
    patch: false
  build:
    project: PAYNLSDK.sln
  before_build:
    - dotnet restore
    - ps: gitversion /l console /output buildserver
    - ps: .\build.ps1
  cache:
    - packages -> **\packages.config      # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
    - '%USERPROFILE%\.nuget\packages -> **\project.json'  # project.json cache
    - C:\ProgramData\chocolatey\bin -> appveyor.yml
    - C:\ProgramData\chocolatey\lib -> appveyor.yml
-
  configuration: AppVeyor
  os: Visual Studio 2017  
  build:
    project: PAYNLSDK.sln
  before_build:
    - dotnet restore
    - ps: gitversion /l console /output buildserver
    - ps: .\build.ps1    
  cache:
    - packages -> **\packages.config      # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
    - '%USERPROFILE%\.nuget\packages -> **\project.json'  # project.json cache
    - C:\ProgramData\chocolatey\bin -> appveyor.yml
    - C:\ProgramData\chocolatey\lib -> appveyor.yml
  test:
    assemblies:
      only:
        - PayNLSdk.Tests/bin/**/PayNLSdk.Tests.dll
