-
  branches:
    only:
      - master
  configuration: AppVeyor
  artifacts:
    - path: '**\RoodFluweel.PAYNLSDK.*.nupkg' # find all NuGet packages recursively
      name: MyApp
    - path: '**\RoodFluweel.PAYNLSDK.*.snupkg' # find all NuGet PDB packages recursively
      name: MyPdb
  deploy:
    - provider: NuGet
      api_key:
        secure: dgTXNdwH249HkbqIRhoSKzkcHOKEi9vczsPFddp197yZ7GvjRhkj+cJ9VrTYxrnc
      skip_symbols: false
      artifact: MyApp
# AppVeyor does not support snupkg yet : https://github.com/appveyor/ci/issues/2753
#    - provider: NuGet
#      api_key:
#        secure: pd9kF0t0Bt6BExgB0t6xEQT9pAlFrRhFZDl6LDGTZjtgaI4nd4ilIongUFWZKLOO
#      skip_symbols: false
#      artifact: MyPdb
  os: Visual Studio 2017
  install:
    - choco install gitversion.portable -pre -y
    - ps: gitversion /l console /output buildserver
  assembly_info:
    patch: false
  dotnet_csproj:
    patch: true
    file: '**\*.csproj'
    version: '{version}'
    package_version: '{version}'
    assembly_version: '{version}'
    file_version: '{version}'
    informational_version: '{version}'
  build:
    project: PAYNLSDK.sln
  before_build:
    - dotnet restore
#    - ps: .\build.ps1
  cache:
    - packages -> **\packages.config      # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
    - '%USERPROFILE%\.nuget\packages -> **\project.json'  # project.json cache
    - C:\ProgramData\chocolatey\bin -> appveyor.yml
    - C:\ProgramData\chocolatey\lib -> appveyor.yml
-
  configuration: AppVeyor
  os: Visual Studio 2017  
  build:
    project: PAYNLSDK.sln
  before_build:
    - dotnet restore
    - ps: gitversion /l console /output buildserver
    - ps: .\build.ps1    
  cache:
    - packages -> **\packages.config      # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
    - '%USERPROFILE%\.nuget\packages -> **\project.json'  # project.json cache
    - C:\ProgramData\chocolatey\bin -> appveyor.yml
    - C:\ProgramData\chocolatey\lib -> appveyor.yml
  test:
    assemblies:
      only:
        - PayNLSdk.Tests/bin/**/PayNLSdk.Tests.dll
