-
  branches:
    only:
      - master
  configuration: Release
  artifacts:
    - path: '**\RoodFluweel.PAYNLSDK.*.nupkg' # find all NuGet packages recursively
      name: MyApp
  deploy:
    provider: NuGet
    api_key:
      secure: pd9kF0t0Bt6BExgB0t6xEQT9pAlFrRhFZDl6LDGTZjtgaI4nd4ilIongUFWZKLOO
    skip_symbols: false
    artifact: MyApp
  os: Visual Studio 2017
  install:
    - choco install gitversion.portable -pre -y
  assembly_info:
    patch: false
  build:
    project: PAYNLSDK\PayNLSdk.csproj
  before_build:
    - dotnet restore
    - ps: .\build.ps1
  dotnet_csproj:
    patch: true
    file: 'PAYNLSDK\PayNLSdk.csproj'    
    package_version: '{version}'
-
  configuration: Debug
  os: Visual Studio 2017  
  build:
    project: PAYNLSDK\PayNLSdk.csproj
  before_build:
    - dotnet restore
    - ps: .\build.ps1
  dotnet_csproj:
    patch: true
    file: 'PAYNLSDK\PayNLSdk.csproj'    
    package_version: '{version}'
