os: Visual Studio 2017

# version format
version: 1.0.{build}

cache:
  - src\packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
  
before_build:
  - nuget restore
