name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore PAYNLSDK\PayNLSdk.csproj
    - name: Build
      run: dotnet build --no-restore PayNLSdk.Tests\PayNLSdk.Tests.csproj
    - name: Test
      run: dotnet test --no-build --verbosity normal PayNLSdk.Tests\PayNLSdk.Tests.csproj
